### ISSUE TITLE
"Could not calculate ReplayGain" and "Failed to calculate ReplayGain for '<Album>'"

### ISSUE THREAD

**Issue by charlydelta** [complexlogic/loudgain#53]
Hello and thanks first of all for this work!

*This is an issue specifically with the MusicBrainz Picard Plugin. If this is the wrong place, please excuse me and let me know where to report my issue instead.*

Ever since ReplayGain 2.0 released, I struggled to get it to work. Up to this point I was not able to make it work at all, and I am close to giving up as I am running out of ideas... I hope somebody can help me with this.

# The Problem

- Whenever I right click on a song and click "Calculate ReplayGain ...", the message "Could not calculate ReplayGain" appears
- Whenever doing so on an album, the message "Failed to calculate ReplayGain for '&lt;Album&gt;'" appears

# Error Logs

To be a bit more specific, the activity log looks like this:

```
2023-02-18 19:33:30,376 - Calculating ReplayGain for 'Eternal Blue'...
2023-02-18 19:33:30,402 - Failed to calculate ReplayGain for 'Eternal Blue.'
2023-02-18 19:33:36,185 - Calculating ReplayGain for /home/chris/.cloud/media/music/spiritbox/2021_eternal_blue/03_yellowjacket.flac...
2023-02-18 19:33:36,209 - Could not calculate ReplayGain.
```

In all cases, an error message like this appears in the log:

```
E: 19:10:59,533 /app/lib/python3.9/site-packages/picard/util/thread.run:66: Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/picard/util/thread.py", line 63, in run
    result = self.func()
  File "/home/chris/.var/app/org.musicbrainz.Picard/config/MusicBrainz/Picard/plugins/replaygain2.zip/replaygain2/__init__.py", line 206, in calculate_replaygain
    raise Exception(f'ReplayGain 2.0: rsgain returned non-zero code ({rc})')
Exception: ReplayGain 2.0: rsgain returned non-zero code (127)
```

# About My System

- My OS is Debian 11 (bullseye) with Linux 5.10.0-20
- I installed Picard as [recommended for Linux](https://picard-docs.musicbrainz.org/en/getting_started/download.html#installing-picard-on-linux) using Flatpak
- I installed rsgain as recommended here in this repo, and it seems to work from the terminal:

```
 $ rsgain --help
Usage: rsgain [OPTIONS] <command> ...
rsgain 3.2 supports writing tags to the following file types:
  FLAC (.flac), Ogg (.ogg, .oga, .spx), Opus (.opus), MP2 (.mp2),
  MP3 (.mp3), MP4 (.m4a), WMA (.wma), WavPack (.wv), APE (.ape),
  WAV (.wav), and AIFF (.aiff, .aif, .snd).

Options:
  -h,   --help              Show this help.
  -v,   --version           Show version number.

Commands:
  easy                    Easy Mode:   Recursively scan a directory with recommended settings.
  custom                  Custom Mode: Scan individual files with custom settings.

Run 'rsgain easy --help' or 'rsgain custom --help' for more information.

Please report any issues to https://github.com/complexlogic/rsgain/issues

  ```

```
 chris@phi-deianeira  ~/media/music/spiritbox  rsgain easy 2021_eternal_blue
[✔] Building directory tree...
[✔] Found 1 directory...
[✔] Scanning directory for files...
[✔] Scanning '2021_eternal_blue/03_yellowjacket.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/02_hurt_you.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/12_constance.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/08_eternal_blue.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/09_we_live_in_a_strange_world.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/06_silk_in_the_strings.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/11_circle_with_me.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/04_the_summit.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/07_holy_roller.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/10_halcyon.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/01_sun_killer.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]
[✔] Scanning '2021_eternal_blue/05_secret_garden.flac'
[✔] Container: raw FLAC [flac]
[✔] Stream #0: FLAC (Free Lossless Audio Codec), 16 bit, 44,100 Hz, 2 ch
 100% [==================================================================================================================================================================================================================================================================================]

Track: 2021_eternal_blue/03_yellowjacket.flac
  Loudness:    -6.19 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -11.81 dB 


Track: 2021_eternal_blue/02_hurt_you.flac
  Loudness:    -5.61 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -12.39 dB 


Track: 2021_eternal_blue/12_constance.flac
  Loudness:    -8.17 LUFS
  Peak:     0.964935 (-0.31 dB)
  Gain:        -9.83 dB 


Track: 2021_eternal_blue/08_eternal_blue.flac
  Loudness:    -6.82 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -11.18 dB 


Track: 2021_eternal_blue/09_we_live_in_a_strange_world.flac
  Loudness:    -7.55 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -10.45 dB 


Track: 2021_eternal_blue/06_silk_in_the_strings.flac
  Loudness:    -5.66 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -12.34 dB 


Track: 2021_eternal_blue/11_circle_with_me.flac
  Loudness:    -6.32 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -11.68 dB 


Track: 2021_eternal_blue/04_the_summit.flac
  Loudness:    -6.11 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -11.89 dB 


Track: 2021_eternal_blue/07_holy_roller.flac
  Loudness:    -7.29 LUFS
  Peak:     0.965088 (-0.31 dB)
  Gain:       -10.71 dB 


Track: 2021_eternal_blue/10_halcyon.flac
  Loudness:    -5.97 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -12.03 dB 


Track: 2021_eternal_blue/01_sun_killer.flac
  Loudness:    -7.34 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -10.66 dB 


Track: 2021_eternal_blue/05_secret_garden.flac
  Loudness:    -5.79 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -12.21 dB 

Album:
  Loudness:    -6.44 LUFS
  Peak:     0.981995 (-0.16 dB)
  Gain:       -11.56 dB 


Scanning Complete
Time Elapsed:      00:00:06
Files Scanned:     12
Clip Adjustments:  0 (0.0% of files)
Average Gain:      -11.43 dB
Average Peak:      0.979164 (-0.18 dB)
Negative Gains:    12 (100.0% of files)
Positive Gains:    0 (0.0% of files)

```

- Since flatpak is sandboxed, I used flatseal in order to try to make the plugin aware of the executable. Here are my settings:
- In flatseal:

![image](https://user-images.githubusercontent.com/46491912/219882012-245cc04d-b510-4a4d-b678-695f0ee890bf.png)

I also thought that maybe it is an issue with dynamically linked libraries not being found within the sandbox, so I added:

![image](https://user-images.githubusercontent.com/46491912/219882051-a01814ea-b28c-4ee6-8900-182d8e0b4cdb.png)

(of no avail)

- Here are my settings in Picard:

![image](https://user-images.githubusercontent.com/46491912/219882083-35f5cdc5-6006-49d2-a395-b29898378c71.png)

# More

I understand that I probably miss some additional important information, even though I tried to be thorough. Please just let me know and I will try to provide anything else needed to track this down.

**Comment by complexlogic** [comment]
Thanks for the detailed information. According to your log, the value 127 is being returned. The only values that rsgain returns are 0 and 1, so we can conclude that rsgain is not being executed. A return value of 127 from a shell usually means command was not found.

Please try the following command in your terminal and let me know the results:
```
/var/run/host/usr/bin/rsgain -v
```

**Comment by charlydelta** [comment]
Thanks for the quick answer! Indeed you seem to be right, thanks for the hint:

I ran this command to execute a given command (rsgain in this case) in the sandbox of flatpak (what is probably the closest it can get to Picard running the command in the sandbox):

```
 $ flatpak run --command="/var/run/host/usr/bin/rsgain" org.musicbrainz.Picard 
/var/run/host/usr/bin/rsgain: error while loading shared libraries: libinih.so.1: cannot open shared object file: No such file or directory
```

Then I printed "$?" to see what the return code of the last executed command was, and here it is:

```
 $ echo $?
127
```

The library is installed though, it just cannot be found within the sandbox:

```
 $ find /usr/lib -iname "*libinih.so.1"
/usr/lib/x86_64-linux-gnu/libinih.so.1
```

So obviously setting `LD_LIBRARY_PATH` in flatseal as shown above does not work correctly...

**Edit**: Actually, it does! I now added "/var/run/host/usr/lib/x86_64-linux-gnu"  to `LD_LIBRARY_PATH`, and now the output is:

```
 $ flatpak run --command="/var/run/host/usr/bin/rsgain" org.musicbrainz.Picard
/var/run/host/usr/bin/rsgain: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
```

I will now try to locate the remaining dynamically linked libraries and manually add them to `LD_LIBRARY_PATH` in flatseal.

**Comment by complexlogic** [comment]
I see the problem now, the [flatpak build script](https://github.com/flathub/org.musicbrainz.Picard/blob/master/org.musicbrainz.Picard.json#L448-L462) is not building the inih library with `-Ddefault_library=static`. A shared library is built by default. Please report this to that repo's issue tracker and link this issue in the description so the maintainers understand the background.

**Comment by charlydelta** [comment]
Ohh it is even more simple than this! I have not seen that by now, **Picard bundles its own version of rsgain**! I just stumbled upon it when I was reading the issues of the flatpak bundling repo you linked.

So all I had to do was to revert everything I did on flatseal, and just type in "rsgain" in the plugin settings instead of the full host-path as shown in the screenshot in the OP. 

My approach did not work anyway because overloading `LD_LIBRARY_PATH` was very unstable and made other things segfault.

So the whole time I was trying to fix issues I created myself back when rsgain was not in Picard... 

I am just happy it works now. **Thanks** @complexlogic for helping out so quickly!

And of course thanks for this great plugin and tool!

**Comment by complexlogic** [comment]
@charlydelta can you please run `which rsgain` in a terminal and let me know the result.

**Comment by charlydelta** [comment]
Sure, here it is:

```
 $ flatpak run --command="which" org.musicbrainz.Picard rsgain
/app/bin/rsgain
```

So now it points to `/app/bin`, whereas earlier I hardcoded it to a host-path in `/var/run/host`. When the new ReplayGain addon released, however, this executable was not yet bundled and had to be installed manually. This is where I messed up.

**Comment by complexlogic** [comment]
OK. I just wanted to make sure it's actually calling the flatpak-bundled rsgain and not the one from the Debian package. Could you temporarily uninstall the rsgain Debian package and run the plugin and confirm that it still works?

**Comment by charlydelta** [comment]
Sure, gladly! I removed the package using `dpkg -r rsgain` (and tried to purge it afterwards, just to be sure). Picard with ReplayGain 2 works as expected:

![image](https://user-images.githubusercontent.com/46491912/219897940-5b684187-b059-475a-9826-cfba9e82888f.png)

**Comment by complexlogic** [comment]
Thanks for confirming. This issue is definitely resolved.
